LLM service bug 27
GoogleCloudPlatform/core-solution-services pull request #62
Opened 2023-10-05 21:41 UTC by lukmanr

With updates to unit tests for LLM Service.  Unit tests are still not passing in LLM Service but I will follow up with another PR for that.

2023-10-07 18:40 UTC, lavjain commented
@lukmanr My fixes for .pylintrc are exactly the same in https://github.com/GoogleCloudPlatform/core-solution-services/pull/50/files LOL

2023-10-07 18:43 UTC, lavjain approved these changes
LGTM

2023-10-08 06:54 UTC, jonchenn requested changes
The latest unit test GHA already covers all microservices.

2023-10-08 06:54 UTC, jonchenn commented on .github/workflows/unit_test_linter_llm_service.yaml
This is not needed with the latest update on unit_test yaml

2023-10-08 06:54 UTC, jonchenn commented on .pylintrc
We use https://github.com/google/styleguide/blob/gh-pages/pylintrc, can you update based on that file?

2023-10-09 13:36 UTC, lukmanr commented on .github/workflows/unit_test_linter_llm_service.yaml
I think it's better to have separate unit test / linter action files. Let's discuss offline.

2023-10-09 13:53 UTC, lukmanr commented on .github/workflows/unit_test_linter_llm_service.yaml
I pushed an update to remove LLM service from the unified unit test GHA for the purposes of this PR.

2023-10-09 14:13 UTC, jonchenn commented on .pylintrc
Let's get this PR merged, we can fix this issue later.

2023-10-09 14:15 UTC, jonchenn commented
Let's get this PR merged first, we'll fix the unit test for LLM in later PR.

2023-10-09 14:15 UTC, merged